/*
 * defaultTitle
 *
 * defaultDescription
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap : IEquatable<Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap>
    { 
        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name="url")]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap)obj);
        }

        /// <summary>
        /// Returns true if Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap instances are equal
        /// </summary>
        /// <param name="other">Instance of Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Url == other.Url ||
                    Url != null &&
                    Url.Equals(other.Url)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap left, Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap left, Lifecycleservicev1enrichmentEventsaddAllAdditionalAttributesMap right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
